export const ADD_SONG_LOADING = "ADD_SONG_LOADING";
export const ADD_SONG_SUCCESS = "ADD_SONG_SUCCESS";
export const ADD_SONG_ERROR = "ADD_SONG_ERROR";
export const GET_SONGS_LOADING = "GET_SONGS_LOADING";
export const GET_SONGS_SUCCESS = "GET_SONGS_SUCCESS";
export const GET_SONGS_ERROR = "GET_SONGS_ERROR";