export const GET_CLIENT_SONGS_LOADING = "GET_CLIENT_SONGS_LOADING";
export const GET_CLIENT_SONGS_SUCCESS = "GET_CLIENT_SONGS_SUCCESS";
export const GET_CLIENT_SONGS_ERROR = "GET_CLIENT_SONGS_ERROR";
export const ADD_CLIENT_REQUESTED_SONG_LOADING =
  "ADD_CLIENT_REQUESTED_SONG_LOADING";
export const ADD_CLIENT_REQUESTED_SONG_SUCCESS =
  "ADD_CLIENT_REQUESTED_SONG_SUCCESS";
export const ADD_CLIENT_REQUESTED_SONG_ERROR =
  "ADD_CLIENT_REQUESTED_SONG_ERROR";
export const EDIT_CLIENT_SONG_LOADING = "EDIT_CLIENT_SONG_LOADING";
export const EDIT_CLIENT_SONG_SUCCESS = "EDIT_CLIENT_SONG_SUCCESS";
export const EDIT_CLIENT_SONG_ERROR = "EDIT_CLIENT_SONG_ERROR";
export const DELETE_CLIENT_SONG_LOADING = "DELETE_CLIENT_SONG_LOADING";
export const DELETE_CLIENT_SONG_SUCCESS = "DELETE_CLIENT_SONG_SUCCESS";
export const DELETE_CLIENT_SONG_ERROR = "DELETE_CLIENT_SONG_ERROR";
export const ADD_CLIENT_DO_NOT_PLAY_SONG_LOADING =
  "ADD_CLIENT_DO_NOT_PLAY_SONG_LOADING";
export const ADD_CLIENT_DO_NOT_PLAY_SONG_SUCCESS =
  "ADD_CLIENT_DO_NOT_PLAY_SONG_SUCCESS";
export const ADD_CLIENT_DO_NOT_PLAY_SONG_ERROR =
  "ADD_CLIENT_DO_NOT_PLAY_SONG_ERROR";
export const SEND_CLIENT_SETLIST_LOADING = "SEND_CLIENT_SETLIST_LOADING";
export const SEND_CLIENT_SETLIST_SUCCESS = "SEND_CLIENT_SETLIST_SUCCESS";
export const SEND_CLIENT_SETLIST_ERROR = "SEND_CLIENT_SETLIST_ERROR";
